// <auto-generated />
using System;
using LearningApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearningApi.Migrations
{
    [DbContext(typeof(LearningDataContext))]
    [Migration("20210804144949_Tweaks")]
    partial class Tweaks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearningApi.Data.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fix Angular App",
                            IsRemoved = false,
                            WhenAdded = new DateTime(2021, 8, 4, 10, 49, 48, 458, DateTimeKind.Local).AddTicks(6082)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Add a POST to the API",
                            IsRemoved = false,
                            WhenAdded = new DateTime(2021, 8, 4, 10, 49, 48, 462, DateTimeKind.Local).AddTicks(811)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
